/**
 * Widths generated by scripts/build-image-variants.mjs and requested by
 * next/image. next.config.ts derives deviceSizes/imageSizes from this list and
 * lib/image-loader.ts maps requests onto the generated files, so the loader
 * can never ask for a width that wasn't built.
 */
export const VARIANT_WIDTHS = [96, 384, 640, 1080, 1920] as const;
