/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-env.d.ts` (hash: 1c50b8eac17eb135218c56a7c798c65d)
interface __BaseEnv_Env {
  LINK_PREVIEW_LIMITER: RateLimit;
  ASSETS: Fetcher;
  GITHUB_CONTENT_BRANCH: 'content';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'GITHUB_CONTENT_BRANCH'>> {}
}
